name: Lint Markdown files

on: ["push", "pull_request"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint Markdown files
      uses: avtodev/markdown-lint@v1
      with:
        config: '.github/workflows/config/markdown-lint.json'
        args: '**/*.md'
